### ISSUE TITLE
Off-canvas ideas

### ISSUE THREAD

**Issue by abstracthat** [rhythnic/maneuver#2]
I like the direction off-canvas is heading. I was just now trying to use it in a new project and here's my thoughts...
1. It would be nice if push actually moved the `.content` instead of squishing the contents into the remaining viewport.
2. A lot of times I don't want a side menu but just a basic hamburger push down from top menu. In this case I still want to define the horizontal breakpoint at which to hide the menu. I'm not sure under what circumstances I would want the height of the window to affect when that get's shown.
3. I don't care for the effect of sliding the menu on top of the content (just my personal preference) but the only way to disable that is to set push to 0px which is a little unintuitive. Not a big deal though.
4. Lastly, I'm not sure if there is an "official" best practice but I usually see camelCase or hyphens for named params rather than underscore.

Great start on this library though and I'm interested in seeing where it goes. Cheers!

**Comment by rhythnic** [comment]
Thanks for your input @abstracthat.  In response to your thoughts:
1.  The concept of push is for the option of having the menu onscreen when there's room.  Personally, I'm not sure when I would push the content off-screen because if I'm going to hide part of the content I'd just assume have the menu go on top of it.
2.  I like this idea a lot.  I agree that a horizontal breakpoint for menus on top and bottom would be much more useful.  This also brings up another point of making rules for the toggle button.  I was considering some basic positioning rules for the buttons if the user specifies the css selector for their toggle button.  Showing/hiding it at a specified breakpoint should be included too.
3.  The relates to point 1.  The issue is whether or not part of the content is hidden, and whether the designer wants to hide the menu-side content or the opposite side.  This could be configurable.  If the configuration grows to have too many options, it might be best to split it into multiple mixins.
4.  No problem.  I'd like to go with the convention whatever that is.

**Comment by rhythnic** [comment]
@abstracthat I just pushed a new branch, oc-horz-bp, that does what we talked about.  In short, there are no more vertical breakpoints.  Push became share, the min width at which the menu and content share the screen.  Push is now a boolean for whether or not to push content off-screen when neither share nor show are in effect.  There's also a new 'visual' folder inside of test, that you can enter and execute 'gulp' to start up the visual test, which is currently a 'preview' of what the documentation will be.  I'll merge everything into master soon, but might include some more things before creating a new version.
